// Generated by CoffeeScript 1.6.3
(function() {
  var socketIOListen, socketio;

  socketio = require('socket.io');

  socketIOListen = function(server) {
    var io;
    io = socketio.listen(server);
    return io.sockets.on('connection', function(socket) {
      return console.log('recieved connection from: ', sockect.id);
    });
  };

  exports.socketIOListen = socketIOListen;

}).call(this);
